#!/bin/bash

jupyter labextension install @jupyter-widgets/jupyterlab-manager \
                             @pyviz/jupyterlab_pyviz \
                             dask-labextension \
                             @ryantam626/jupyterlab_code_formatter \
                             jupyterlab-topbar-extension \
                             jupyterlab-system-monitor \
                             --no-build

jupyter serverextension enable --py jupyterlab_code_formatter

jupyter lab build